[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.8",
    "pydantic>=2.10.6",
    "pytest>=8.3.4",
    "duckdb",
    "jose>=1.0.0",
    "redis>=5.2.1",
]
